<a href="https://colab.research.google.com/github/jiraroj-wir/MUIC-ICCS261-Principles-of-Data-Science/blob/main/Jiraroj_PreparingData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Preparing Data with pandas

## Section 1: Load and explore the dataset

**References**
- Adapted from https://www.packtpub.com/big-data-and-business-intelligence/data-visualisation-python by K. Bunchongchit, last modified on Jun 1, 2025
- Data from https://data.worldbank.org/indicator/SP.POP.TOTL (Do **not** download the data from this link for the assignment; it is not in the right format for pandas unless you would like some challenge.)

Last modified by Jiraroj Wiruchpongsanon (6781617) on 13/10/2026

In this activity, you will consolidate the skills you've acquired in the last exercise and use Pandas to do some very basic mathematical calculations on our `world_population.csv` dataset. Pandas have a consistent API, so it should be rather easy to transfer your knowledge of the mean method to median and variance.    

<span style="color:purple">**Commands that you need can be found at**</span>
- [10 minutes to pandas](https://pandas.pydata.org/docs/user_guide/10min.html)
- [Python For Data Analysis and Manipulation: pandas](https://www.topcoder.com/thrive/articles/python-for-data-analysis-and-manipulation-pandas)

Your already existing knowledge of NumPy will also come in handy. In addition, additional research on the Internet may be required for more diffcult tasks towars the end of the notebook.

### Rules:
1. Assign the result of each task to the given variable in each cell. In other words, add the code for each task after the equal sign. Of course, you can use more variables to hold intermediate values before the final output.
2. ####  <span style="color:red">If other modules, such as <code>statistics</code> and <code>numpy</code>, and Python's repetition in any form (while, for, comprehension) are used to complete this assignment, it will not be graded.</span>
3. Do not change the index column at any time.
4. Do not reload the dataset from the file.

### Loading the dataset
1. Import the necessary dependencies.

In [1]:
import pandas as pd

- 1.1 Run this code to connect to the data cloud drive if you are doing this assignment via Google Colab. If you use a desktop IDE and prefer a local file, just skip this step.

In [2]:
CSV_URL = 'https://drive.google.com/uc?export=download&id=1dynWuU_V3s0qrCRfveRsoKPzcxqBpG9R'

2. Load the dataset by setting the first column to be the row label.
   - If you are using **Google Colab**, run the code below.

In [3]:
df = pd.read_csv(CSV_URL, index_col=0)
df

,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
Country Name,,,,,,,,,,,,,,,,,,,,,
Aruba,ABW,"Population, total",SP.POP.TOTL,54208.0,55434.0,56234.0,56699.0,57029.0,57357.0,57702.0,...,102565.0,103165.0,103776.0,104339.0,104865.0,105361.0,105846.0,106310.0,106766.0,107195.0
Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,130836765.0,134159786.0,137614644.0,141202036.0,144920186.0,148769974.0,152752671.0,...,547482863.0,562601578.0,578075373.0,593871847.0,609978946.0,626392880.0,643090131.0,660046272.0,677243299.0,694665117.0
Afghanistan,AFG,"Population, total",SP.POP.TOTL,8996967.0,9169406.0,9351442.0,9543200.0,9744772.0,9956318.0,10174840.0,...,31161378.0,32269592.0,33370804.0,34413603.0,35383028.0,36296111.0,37171922.0,38041757.0,38928341.0,39835428.0
Africa Western and Central,AFW,"Population, total",SP.POP.TOTL,96396419.0,98407221.0,100506960.0,102691339.0,104953470.0,107289875.0,109701811.0,...,370243017.0,380437896.0,390882979.0,401586651.0,412551299.0,423769930.0,435229381.0,446911598.0,458803476.0,470898870.0
Angola,AGO,"Population, total",SP.POP.TOTL,5454938.0,5531451.0,5608499.0,5679409.0,5734995.0,5770573.0,5781305.0,...,25107925.0,26015786.0,26941773.0,27884380.0,28842482.0,29816769.0,30809787.0,31825299.0,32866268.0,33933611.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Kosovo,XKX,"Population, total",SP.POP.TOTL,947000.0,966000.0,994000.0,1022000.0,1050000.0,1078000.0,1106000.0,...,1807106.0,1818117.0,1812771.0,1788196.0,1777557.0,1791003.0,1797085.0,1788878.0,1790133.0,1806279.0
"Yemen, Rep.",YEM,"Population, total",SP.POP.TOTL,5315351.0,5393034.0,5473671.0,5556767.0,5641598.0,5727745.0,5816241.0,...,24473176.0,25147112.0,25823488.0,26497881.0,27168210.0,27834811.0,28498683.0,29161922.0,29825968.0,30490639.0
South Africa,ZAF,"Population, total",SP.POP.TOTL,17099836.0,17524533.0,17965733.0,18423157.0,18896303.0,19384838.0,19888259.0,...,52832659.0,53687125.0,54544184.0,55386369.0,56207649.0,57009751.0,57792520.0,58558267.0,59308690.0,60041996.0
Zambia,ZMB,"Population, total",SP.POP.TOTL,3070780.0,3164330.0,3260645.0,3360099.0,3463211.0,3570466.0,3681953.0,...,14465148.0,14926551.0,15399793.0,15879370.0,16363449.0,16853608.0,17351714.0,17861034.0,18383956.0,18920657.0
Zimbabwe,ZWE,"Population, total",SP.POP.TOTL,3776679.0,3905038.0,4039209.0,4178726.0,4322854.0,4471178.0,4623340.0,...,13115149.0,13350378.0,13586710.0,13814642.0,14030338.0,14236599.0,14438812.0,14645473.0,14862927.0,15092171.0

- If you are running a local IDE and prefer a local file,

   * 2.1 download <a href="https://drive.google.com/file/d/1dynWuU_V3s0qrCRfveRsoKPzcxqBpG9R/view?usp=drive_link">the data file</a> and place it in the same folder as this notebook.
   * 2.2 Make a code cell underneath this cell and run the code below. Adjust your data file path if necessary.
```
df = pd.read_csv('world_population.csv', index_col=0)
```

3. Look at the first two rows of the dataset <span style="color:purple; font-weight:bold">without indexing and slicing</span>.
> pandas has its own function to do this beatifully.

In [4]:
sol3 = df.head(2)
sol3

,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
Country Name,,,,,,,,,,,,,,,,,,,,,
Aruba,ABW,"Population, total",SP.POP.TOTL,54208.0,55434.0,56234.0,56699.0,57029.0,57357.0,57702.0,...,102565.0,103165.0,103776.0,104339.0,104865.0,105361.0,105846.0,106310.0,106766.0,107195.0
Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,130836765.0,134159786.0,137614644.0,141202036.0,144920186.0,148769974.0,152752671.0,...,547482863.0,562601578.0,578075373.0,593871847.0,609978946.0,626392880.0,643090131.0,660046272.0,677243299.0,694665117.0

4.1 Generate the descriptive statistics for **numerical** columns of the dataset. You need only one function (one line of code) to do this.
> Hint: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html

In [5]:
sol4_1 = df.describe()
sol4_1

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
count,2.640000e+02,2.640000e+02,2.640000e+02,2.640000e+02,2.640000e+02,2.640000e+02,2.640000e+02,2.640000e+02,2.640000e+02,2.640000e+02,...,2.640000e+02,2.640000e+02,2.640000e+02,2.640000e+02,2.640000e+02,2.640000e+02,2.640000e+02,2.640000e+02,2.640000e+02,2.640000e+02
mean,1.172174e+08,1.187633e+08,1.208717e+08,1.234910e+08,1.261315e+08,1.288372e+08,1.316853e+08,1.345256e+08,1.374350e+08,1.404490e+08,...,2.874902e+08,2.912969e+08,2.951160e+08,2.989277e+08,3.027560e+08,3.065980e+08,3.103591e+08,3.140425e+08,3.176734e+08,3.210893e+08
std,3.695745e+08,3.739180e+08,3.804316e+08,3.889142e+08,3.974401e+08,4.062000e+08,4.155171e+08,4.247722e+08,4.342805e+08,4.441772e+08,...,9.017511e+08,9.129343e+08,9.241050e+08,9.352101e+08,9.463321e+08,9.575052e+08,9.683483e+08,9.788967e+08,9.891628e+08,9.988295e+08
min,2.833000e+03,3.077000e+03,3.367000e+03,3.703000e+03,4.063000e+03,4.460000e+03,4.675000e+03,4.922000e+03,5.194000e+03,5.461000e+03,...,1.013600e+04,1.020800e+04,1.028900e+04,1.037400e+04,1.047400e+04,1.057700e+04,1.067800e+04,1.076400e+04,1.083400e+04,1.087300e+04
25%,5.022802e+05,5.109642e+05,5.206540e+05,5.311622e+05,5.421252e+05,5.533362e+05,5.647475e+05,5.823645e+05,5.981078e+05,6.100030e+05,...,1.539939e+06,1.574621e+06,1.609909e+06,1.645868e+06,1.689616e+06,1.716772e+06,1.740174e+06,1.751950e+06,1.767996e+06,1.791783e+06
50%,3.718330e+06,3.826398e+06,3.929109e+06,4.015834e+06,4.124521e+06,4.242788e+06,4.326013e+06,4.387887e+06,4.474171e+06,4.550402e+06,...,9.824808e+06,9.948838e+06,1.001582e+07,1.022085e+07,1.036160e+07,1.040671e+07,1.045548e+07,1.047907e+07,1.052565e+07,1.054019e+07
75%,2.636053e+07,2.721235e+07,2.808607e+07,2.890669e+07,2.972333e+07,3.055227e+07,3.134845e+07,3.200449e+07,3.244145e+07,3.277149e+07,...,6.057984e+07,6.120753e+07,6.174243e+07,6.182699e+07,6.187352e+07,6.191725e+07,6.193141e+07,6.150589e+07,6.157091e+07,6.295547e+07
max,3.032156e+09,3.071596e+09,3.124561e+09,3.189656e+09,3.255146e+09,3.322047e+09,3.392098e+09,3.461620e+09,3.532783e+09,3.606554e+09,...,7.089255e+09,7.175500e+09,7.261847e+09,7.347679e+09,7.433651e+09,7.519371e+09,7.602716e+09,7.683806e+09,7.763933e+09,7.836631e+09

5. Generate the descriptive statistics for **categorial** columns of the dataset. You need only one function (one line of code) to do this.
> Hint: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html

In [6]:
sol4_2 = df.describe(exclude='number')
sol4_2

       Country Code     Indicator Name Indicator Code
count           266                266            266
unique          266                  1              1
top             ABW  Population, total    SP.POP.TOTL
freq              1                266            266

---
## Section 2: Indexing, Slicing, and Iterating

In order to get some good and understandable insights into our dataset, we need to be able to explicitly index, slice and iterate our data to e.g. compare several countries in terms of population density growth.   

After looking at the distinct operations we want to display the countries Germany, Singapore, United States, and India with their total population of years 1970, 1990, 2010.


### Indexing

Since we need several rows and columns of our dataset to complete the given task, we have to use indexing to get the right rows and columns.   
We need:
- the row of the USA
- the second to last row
- the column of year 2000 as Series
- the total population of India in 2000

5. Index the USA row as a Series <span style="color:purple; font-weight:bold">using the label</span>.

In [7]:
sol5 = df.loc['United States']
sol5

Country Code                    USA
Indicator Name    Population, total
Indicator Code          SP.POP.TOTL
1960                    180671000.0
1961                    183691000.0
                        ...
2017                    325122128.0
2018                    326838199.0
2019                    328329953.0
2020                    331501080.0
2021                    331893745.0
Name: United States, Length: 65, dtype: object

6. Index the column of 2000 as a Series <span style="color:purple;">**using the label**</span> (without using ```loc``` and ```iloc```).

In [8]:
sol6 = df['2000']
sol6

Country Name
Aruba                              90866.0
Africa Eastern and Southern    398113044.0
Afghanistan                     20779957.0
Africa Western and Central     267214544.0
Angola                          16395477.0
                                  ...
Kosovo                           1700000.0
Yemen, Rep.                     17409071.0
South Africa                    44967713.0
Zambia                          10415942.0
Zimbabwe                        11881482.0
Name: 2000, Length: 266, dtype: float64

7. Index the total population of India in 2000 as a **Dataframe** <span style="color:purple; font-weight:bold">using labels</span>.

In [9]:
sol7 = df.loc[['India'], ['2000']]
sol7

                      2000
Country Name
India         1.056576e+09

>**Note:**   
>Using single brackets to index columns (like with NumPy) we will get a pandas Series object.   
When using double brackets to do indexing, a DataFrame will be returned. This way we can also index several elements with one query.
>
>When comparing the output of the Dataframe query to the Series query, we can see the difference between Series and DataFrames

8. Index the total population of India in 2000 as a **Series** <span style="color:purple; font-weight:bold">using  labels</span>.

In [10]:
sol8 = df.loc['India', ['2000']]
sol8

2000    1.056576e+09
Name: India, dtype: float64

---
### Slicing

Other than the single rows and columns and we also need to get some Subsets of the dataset.   
Here we want slices:
- the countries in row 2 to 5
- countries Germany, Singapore, United States, and India
- Germany, Singapore, United States, and India with their total population of years 1970, 1990, 2010

9. Get the last two rows using a pandas function, no indexing or slicing.

In [11]:
sol9 = df.tail(2)
sol9

,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
Country Name,,,,,,,,,,,,,,,,,,,,,
Zambia,ZMB,"Population, total",SP.POP.TOTL,3070780.0,3164330.0,3260645.0,3360099.0,3463211.0,3570466.0,3681953.0,...,14465148.0,14926551.0,15399793.0,15879370.0,16363449.0,16853608.0,17351714.0,17861034.0,18383956.0,18920657.0
Zimbabwe,ZWE,"Population, total",SP.POP.TOTL,3776679.0,3905038.0,4039209.0,4178726.0,4322854.0,4471178.0,4623340.0,...,13115149.0,13350378.0,13586710.0,13814642.0,14030338.0,14236599.0,14438812.0,14645473.0,14862927.0,15092171.0

10. Slice countries of rows 2 to 5.

In [12]:
sol10 = df.iloc[1:5]
sol10

,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
Country Name,,,,,,,,,,,,,,,,,,,,,
Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,130836765.0,134159786.0,137614644.0,141202036.0,144920186.0,148769974.0,152752671.0,...,547482863.0,562601578.0,578075373.0,593871847.0,609978946.0,626392880.0,643090131.0,660046272.0,677243299.0,694665117.0
Afghanistan,AFG,"Population, total",SP.POP.TOTL,8996967.0,9169406.0,9351442.0,9543200.0,9744772.0,9956318.0,10174840.0,...,31161378.0,32269592.0,33370804.0,34413603.0,35383028.0,36296111.0,37171922.0,38041757.0,38928341.0,39835428.0
Africa Western and Central,AFW,"Population, total",SP.POP.TOTL,96396419.0,98407221.0,100506960.0,102691339.0,104953470.0,107289875.0,109701811.0,...,370243017.0,380437896.0,390882979.0,401586651.0,412551299.0,423769930.0,435229381.0,446911598.0,458803476.0,470898870.0
Angola,AGO,"Population, total",SP.POP.TOTL,5454938.0,5531451.0,5608499.0,5679409.0,5734995.0,5770573.0,5781305.0,...,25107925.0,26015786.0,26941773.0,27884380.0,28842482.0,29816769.0,30809787.0,31825299.0,32866268.0,33933611.0

11. Slice rows Germany, Singapore, United States, and India <span style="color:purple; font-weight:bold">using  labels</span>.

In [13]:
sol11 = df.loc[['Germany', 'Singapore', 'United States', 'India']]
sol11

,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
Country Name,,,,,,,,,,,,,,,,,,,,,
Germany,DEU,"Population, total",SP.POP.TOTL,72814900.0,73377632.0,74025784.0,74714353.0,75318337.0,75963695.0,76600311.0,...,8.042582e+07,8.064560e+07,8.098250e+07,8.168661e+07,8.234867e+07,8.265700e+07,8.290578e+07,8.309296e+07,8.316087e+07,8.312928e+07
Singapore,SGP,"Population, total",SP.POP.TOTL,1646400.0,1702400.0,1750200.0,1795000.0,1841600.0,1886900.0,1934400.0,...,5.312437e+06,5.399162e+06,5.469724e+06,5.535002e+06,5.607283e+06,5.612253e+06,5.638676e+06,5.703569e+06,5.685807e+06,5.453566e+06
United States,USA,"Population, total",SP.POP.TOTL,180671000.0,183691000.0,186538000.0,189242000.0,191889000.0,194303000.0,196560000.0,...,3.138777e+08,3.160599e+08,3.183863e+08,3.207390e+08,3.230718e+08,3.251221e+08,3.268382e+08,3.283300e+08,3.315011e+08,3.318937e+08
India,IND,"Population, total",SP.POP.TOTL,450547675.0,459642166.0,469077191.0,478825602.0,488848139.0,499123328.0,509631509.0,...,1.265780e+09,1.280842e+09,1.295601e+09,1.310152e+09,1.324517e+09,1.338677e+09,1.352642e+09,1.366418e+09,1.380004e+09,1.393409e+09

12. Slice a subset of Germany, Singapore, United States, and India for years 1970, 1990, 2010 <span style="color:purple; font-weight:bold">using  labels</span>.

In [14]:
sol12 = df.loc[['Germany', 'Singapore', 'United States', 'India'], ['1970', '1990', '2010']]
sol12

                      1970         1990          2010
Country Name
Germany         78169289.0   79433029.0  8.177693e+07
Singapore        2074507.0    3047132.0  5.076732e+06
United States  205052000.0  249623000.0  3.093271e+08
India          555189797.0  873277799.0  1.234281e+09

---
## Section 3: Use pandas to compute the Mean, Median, and Variance
### Mean
Here we learn how to manipulate data in the same scenarios as we have done in NumPy. Notice both the similaity and difference.

>**Note:**   
>`.iloc()` and `.loc()` are two important methods when indexing with Pandas. They allow making precise selections of data based on either the integer value index (`iloc`) or the index column (`loc`), which in our case is the country name column.

13. Calculate the mean of the third row as a ```float64``` by <span style="color:purple; font-weight:bold">using only `.iloc()` and/or `.loc()`</span> to access the data.

In [15]:
sol13 = df.iloc[2, 3:].mean()
sol13

np.float64(19040298.20967742)

14. Calculate the mean of the country Germany as a ```float64``` by <span style="color:purple; font-weight:bold">using only `.iloc()` and/or `.loc()`</span> to access the data.

In [16]:
sol14 = df.loc['Germany', '1960':'2021'].mean()
sol14

np.float64(79666851.96774194)

---
### Median

>**Notes:**   
>- When handling larger datasets, the order in which methods get executed definitely matters.   
Think about what `.head(10)` does for a moment, it simply takes your dataset and returns the first 10 rows of it, cutting down your input to the `.mean()` method drastically.   
This will definitely have an impact when using more memory intensive calculations, so keep an eye on the order.
>- Slicing can be done in the same way as with NumPy.   
>`dataset[1:3]` will return the second and third row of our dataset.

15. Calculate the median of the last row by <span style="color:purple; font-weight:bold">using `.iloc()` and/or `.loc()`</span> to access the data. The result must be of type ```float64```.

In [17]:
sol15 = df.iloc[-1, 3:].median()
sol15

np.float64(10556708.5)

16. Calculate the medians of the first 10 countries <span style="color:purple; font-weight:bold"> (median by row)</span>.

In [18]:
sol16 = df.head(10).median(axis=1, numeric_only=True)
sol16

Country Name
Aruba                              63823.5
Africa Eastern and Southern    309021351.5
Afghanistan                     13383780.0
Africa Western and Central     207568066.0
Angola                          12048643.0
Albania                          2884903.5
Andorra                            55587.0
Arab World                     225692521.0
United Arab Emirates             1882798.0
Argentina                       32848825.0
dtype: float64

---
### Variance

17. Calculate the variances of the last 5 columns (variance by column).

In [19]:
sol17 = df.iloc[:, -5:].var()
sol17

2017    9.168162e+17
2018    9.376984e+17
2019    9.582388e+17
2020    9.784430e+17
2021    9.976603e+17
dtype: float64

---
The following example computes the mean population in 2015 using pandas.

In [20]:
# pandas-only example: mean population in 2015
print("Pandas", df["2015"].mean())

Pandas 298927728.8068182

---
## Section 4: Filtering, Sorting, and Reshaping

Following up on the last activity, we are asked to deliver some more complex operations.   
We will, therefore, continue to work with the same dataset, our `world_population.csv`.

### Filtering

To get better insights into our dataset, we want to only look at the value that fulfills certain conditions.   
Our client reaches out to us and asks us to provide lists of values that fulfills these conditions:
- a new dataset that only contains 1970, 2000, and 2015 as columns
- all countries that in 2000 had a greater total population than 5,000,000
- a new dataset that only contains years 2000 and later
- a new dataset that only contains countries that start with `A`
- a new dataset that only contains countries that contain the word `land`

18. Filter columns 1970, 2000, and 2015.

In [21]:
sol18 = df.filter(items=['1970', '2000', '2015'])
sol18

                                    1970         2000         2015
Country Name
Aruba                            59070.0      90866.0     104339.0
Africa Eastern and Southern  170257189.0  398113044.0  593871847.0
Afghanistan                   11173654.0   20779957.0   34413603.0
Africa Western and Central   120269044.0  267214544.0  401586651.0
Angola                         5890360.0   16395477.0   27884380.0
...                                  ...          ...          ...
Kosovo                         1219000.0    1700000.0    1788196.0
Yemen, Rep.                    6193379.0   17409071.0   26497881.0
South Africa                  22069783.0   44967713.0   55386369.0
Zambia                         4179062.0   10415942.0   15879370.0
Zimbabwe                       5289312.0   11881482.0   13814642.0

[266 rows x 3 columns]

19. Filter countries that had a greater total population than 5,000,000 in 2000.

In [22]:
sol19 = df.loc[df['2000'] > 5_000_000]
sol19

,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
Country Name,,,,,,,,,,,,,,,,,,,,,
Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,1.308368e+08,1.341598e+08,1.376146e+08,1.412020e+08,1.449202e+08,1.487700e+08,1.527527e+08,...,5.474829e+08,5.626016e+08,5.780754e+08,5.938718e+08,6.099789e+08,6.263929e+08,6.430901e+08,6.600463e+08,6.772433e+08,6.946651e+08
Afghanistan,AFG,"Population, total",SP.POP.TOTL,8.996967e+06,9.169406e+06,9.351442e+06,9.543200e+06,9.744772e+06,9.956318e+06,1.017484e+07,...,3.116138e+07,3.226959e+07,3.337080e+07,3.441360e+07,3.538303e+07,3.629611e+07,3.717192e+07,3.804176e+07,3.892834e+07,3.983543e+07
Africa Western and Central,AFW,"Population, total",SP.POP.TOTL,9.639642e+07,9.840722e+07,1.005070e+08,1.026913e+08,1.049535e+08,1.072899e+08,1.097018e+08,...,3.702430e+08,3.804379e+08,3.908830e+08,4.015867e+08,4.125513e+08,4.237699e+08,4.352294e+08,4.469116e+08,4.588035e+08,4.708989e+08
Angola,AGO,"Population, total",SP.POP.TOTL,5.454938e+06,5.531451e+06,5.608499e+06,5.679409e+06,5.734995e+06,5.770573e+06,5.781305e+06,...,2.510792e+07,2.601579e+07,2.694177e+07,2.788438e+07,2.884248e+07,2.981677e+07,3.080979e+07,3.182530e+07,3.286627e+07,3.393361e+07
Arab World,ARB,"Population, total",SP.POP.TOTL,9.219772e+07,9.472454e+07,9.733444e+07,1.000342e+08,1.028328e+08,1.057364e+08,1.087586e+08,...,3.714376e+08,3.796965e+08,3.878998e+08,3.960283e+08,4.040429e+08,4.119428e+08,4.198520e+08,4.278703e+08,4.360807e+08,4.445178e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
World,WLD,"Population, total",SP.POP.TOTL,3.032156e+09,3.071596e+09,3.124561e+09,3.189656e+09,3.255146e+09,3.322047e+09,3.392098e+09,...,7.089255e+09,7.175500e+09,7.261847e+09,7.347679e+09,7.433651e+09,7.519371e+09,7.602716e+09,7.683806e+09,7.763933e+09,7.836631e+09
"Yemen, Rep.",YEM,"Population, total",SP.POP.TOTL,5.315351e+06,5.393034e+06,5.473671e+06,5.556767e+06,5.641598e+06,5.727745e+06,5.816241e+06,...,2.447318e+07,2.514711e+07,2.582349e+07,2.649788e+07,2.716821e+07,2.783481e+07,2.849868e+07,2.916192e+07,2.982597e+07,3.049064e+07
South Africa,ZAF,"Population, total",SP.POP.TOTL,1.709984e+07,1.752453e+07,1.796573e+07,1.842316e+07,1.889630e+07,1.938484e+07,1.988826e+07,...,5.283266e+07,5.368712e+07,5.454418e+07,5.538637e+07,5.620765e+07,5.700975e+07,5.779252e+07,5.855827e+07,5.930869e+07,6.004200e+07
Zambia,ZMB,"Population, total",SP.POP.TOTL,3.070780e+06,3.164330e+06,3.260645e+06,3.360099e+06,3.463211e+06,3.570466e+06,3.681953e+06,...,1.446515e+07,1.492655e+07,1.539979e+07,1.587937e+07,1.636345e+07,1.685361e+07,1.735171e+07,1.786103e+07,1.838396e+07,1.892066e+07
Zimbabwe,ZWE,"Population, total",SP.POP.TOTL,3.776679e+06,3.905038e+06,4.039209e+06,4.178726e+06,4.322854e+06,4.471178e+06,4.623340e+06,...,1.311515e+07,1.335038e+07,1.358671e+07,1.381464e+07,1.403034e+07,1.423660e+07,1.443881e+07,1.464547e+07,1.486293e+07,1.509217e+07

20. Filter for years 2000 and later <span style="color:purple; font-weight:bold">without indexing and slicing</span>.

In [23]:
sol20 = df.filter(regex=r'^2[0-9]{3}$', axis='columns')
sol20

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
Country Name,,,,,,,,,,,,,,,,,,,,,
Aruba,90866.0,92892.0,94992.0,97016.0,98744.0,100028.0,100830.0,101226.0,101362.0,101452.0,...,102565.0,103165.0,103776.0,104339.0,104865.0,105361.0,105846.0,106310.0,106766.0,107195.0
Africa Eastern and Southern,398113044.0,408522129.0,419223717.0,430246635.0,441630149.0,453404076.0,465581372.0,478166911.0,491173160.0,504604672.0,...,547482863.0,562601578.0,578075373.0,593871847.0,609978946.0,626392880.0,643090131.0,660046272.0,677243299.0,694665117.0
Afghanistan,20779957.0,21606992.0,22600774.0,23680871.0,24726689.0,25654274.0,26433058.0,27100542.0,27722281.0,28394806.0,...,31161378.0,32269592.0,33370804.0,34413603.0,35383028.0,36296111.0,37171922.0,38041757.0,38928341.0,39835428.0
Africa Western and Central,267214544.0,274433894.0,281842480.0,289469530.0,297353098.0,305520588.0,313985474.0,322741656.0,331772330.0,341050537.0,...,370243017.0,380437896.0,390882979.0,401586651.0,412551299.0,423769930.0,435229381.0,446911598.0,458803476.0,470898870.0
Angola,16395477.0,16945753.0,17519418.0,18121477.0,18758138.0,19433604.0,20149905.0,20905360.0,21695636.0,22514275.0,...,25107925.0,26015786.0,26941773.0,27884380.0,28842482.0,29816769.0,30809787.0,31825299.0,32866268.0,33933611.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Kosovo,1700000.0,1701154.0,1702310.0,1703466.0,1704622.0,1705780.0,1719536.0,1733404.0,1747383.0,1761474.0,...,1807106.0,1818117.0,1812771.0,1788196.0,1777557.0,1791003.0,1797085.0,1788878.0,1790133.0,1806279.0
"Yemen, Rep.",17409071.0,17918369.0,18443684.0,18985001.0,19540096.0,20107416.0,20687648.0,21282514.0,21892149.0,22516464.0,...,24473176.0,25147112.0,25823488.0,26497881.0,27168210.0,27834811.0,28498683.0,29161922.0,29825968.0,30490639.0
South Africa,44967713.0,45571272.0,46150913.0,46719203.0,47291610.0,47880595.0,48489464.0,49119766.0,49779472.0,50477013.0,...,52832659.0,53687125.0,54544184.0,55386369.0,56207649.0,57009751.0,57792520.0,58558267.0,59308690.0,60041996.0
Zambia,10415942.0,10692197.0,10971704.0,11256740.0,11550641.0,11856244.0,12173518.0,12502958.0,12848531.0,13215142.0,...,14465148.0,14926551.0,15399793.0,15879370.0,16363449.0,16853608.0,17351714.0,17861034.0,18383956.0,18920657.0
Zimbabwe,11881482.0,11923906.0,11954293.0,11982219.0,12019911.0,12076697.0,12155496.0,12255920.0,12379553.0,12526964.0,...,13115149.0,13350378.0,13586710.0,13814642.0,14030338.0,14236599.0,14438812.0,14645473.0,14862927.0,15092171.0

21. Filter countries that start with A.

In [24]:
sol21 = df.filter(regex=r'^A.*$', axis='index')
sol21

,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
Country Name,,,,,,,,,,,,,,,,,,,,,
Aruba,ABW,"Population, total",SP.POP.TOTL,54208.0,55434.0,56234.0,56699.0,57029.0,57357.0,57702.0,...,102565.0,103165.0,103776.0,104339.0,104865.0,105361.0,105846.0,106310.0,106766.0,107195.0
Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,130836765.0,134159786.0,137614644.0,141202036.0,144920186.0,148769974.0,152752671.0,...,547482863.0,562601578.0,578075373.0,593871847.0,609978946.0,626392880.0,643090131.0,660046272.0,677243299.0,694665117.0
Afghanistan,AFG,"Population, total",SP.POP.TOTL,8996967.0,9169406.0,9351442.0,9543200.0,9744772.0,9956318.0,10174840.0,...,31161378.0,32269592.0,33370804.0,34413603.0,35383028.0,36296111.0,37171922.0,38041757.0,38928341.0,39835428.0
Africa Western and Central,AFW,"Population, total",SP.POP.TOTL,96396419.0,98407221.0,100506960.0,102691339.0,104953470.0,107289875.0,109701811.0,...,370243017.0,380437896.0,390882979.0,401586651.0,412551299.0,423769930.0,435229381.0,446911598.0,458803476.0,470898870.0
Angola,AGO,"Population, total",SP.POP.TOTL,5454938.0,5531451.0,5608499.0,5679409.0,5734995.0,5770573.0,5781305.0,...,25107925.0,26015786.0,26941773.0,27884380.0,28842482.0,29816769.0,30809787.0,31825299.0,32866268.0,33933611.0
Albania,ALB,"Population, total",SP.POP.TOTL,1608800.0,1659800.0,1711319.0,1762621.0,1814135.0,1864791.0,1914573.0,...,2900401.0,2895092.0,2889104.0,2880703.0,2876101.0,2873457.0,2866376.0,2854191.0,2837849.0,2811666.0
Andorra,AND,"Population, total",SP.POP.TOTL,13410.0,14378.0,15379.0,16407.0,17466.0,18542.0,19646.0,...,82427.0,80770.0,79213.0,77993.0,77295.0,76997.0,77008.0,77146.0,77265.0,77354.0
Arab World,ARB,"Population, total",SP.POP.TOTL,92197715.0,94724540.0,97334438.0,100034191.0,102832792.0,105736428.0,108758634.0,...,371437642.0,379696477.0,387899835.0,396028301.0,404042892.0,411942825.0,419851989.0,427870273.0,436080728.0,444517783.0
Argentina,ARG,"Population, total",SP.POP.TOTL,20481781.0,20817270.0,21153042.0,21488916.0,21824427.0,22159644.0,22494031.0,...,41733271.0,42202935.0,42669500.0,43131966.0,43590368.0,44044811.0,44494502.0,44938712.0,45376763.0,45808747.0
Armenia,ARM,"Population, total",SP.POP.TOTL,1874119.0,1941498.0,2009524.0,2077584.0,2145004.0,2211316.0,2276038.0,...,2884239.0,2897593.0,2912403.0,2925559.0,2936147.0,2944789.0,2951741.0,2957728.0,2963234.0,2968128.0
American Samoa,ASM,"Population, total",SP.POP.TOTL,20127.0,20605.0,21246.0,22029.0,22850.0,23675.0,24473.0,...,55669.0,55717.0,55791.0,55806.0,55739.0,55617.0,55461.0,55312.0,55197.0,55103.0
Antigua and Barbuda,ATG,"Population, total",SP.POP.TOTL,54132.0,55005.0,55849.0,56701.0,57641.0,58699.0,59912.0,...,90407.0,91510.0,92562.0,93571.0,94520.0,95425.0,96282.0,97115.0,97928.0,98728.0
Australia,AUS,"Population, total",SP.POP.TOTL,10276477.0,10483000.0,10742000.0,10950000.0,11167000.0,11388000.0,11651000.0,...,22733465.0,23128129.0,23475686.0,23815995.0,24190907.0,24601860.0,24982688.0,25365745.0,25693267.0,25739256.0
Austria,AUT,"Population, total",SP.POP.TOTL,7047539.0,7086299.0,7129864.0,7175811.0,7223801.0,7270889.0,7322066.0,...,8429991.0,8479823.0,8546356.0,8642699.0,8736668.0,8797566.0,8840521.0,8879920.0,8916864.0,8956279.0
Azerbaijan,AZE,"Population, total",SP.POP.TOTL,3895398.0,4030325.0,4171428.0,4315127.0,4456691.0,4592601.0,4721528.0,...,9295784.0,9416801.0,9535079.0,9649341.0,9757812.0,9854033.0,9939771.0,10024283.0,10093121.0,10145212.0
Algeria,DZA,"Population, total",SP.POP.TOTL,11057864.0,11336336.0,11619828.0,11912800.0,12221675.0,12550880.0,12902626.0,...,37383899.0,38140135.0,38923688.0,39728020.0,40551398.0,41389174.0,42228415.0,43053054.0,43851043.0,44616626.0

22. Filter countries that contain the word land.

In [25]:
sol22 = df.filter(regex=r'^.*[lL]and.*$', axis=0)
sol22

,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
Country Name,,,,,,,,,,,,,,,,,,,,,
Switzerland,CHE,"Population, total",SP.POP.TOTL,5327827.0,5434294.0,5573815.0,5694247.0,5789228.0,5856472.0,5918002.0,...,7996861.0,8089346.0,8188649.0,8282396.0,8373338.0,8451840.0,8514329.0,8575280.0,8636561.0,8697723.0
Channel Islands,CHI,"Population, total",SP.POP.TOTL,109419.0,110398.0,111464.0,112591.0,113777.0,114989.0,116229.0,...,162051.0,163039.0,164107.0,165387.0,166922.0,168666.0,170496.0,172264.0,173859.0,175244.0
Cayman Islands,CYM,"Population, total",SP.POP.TOTL,7870.0,8024.0,8141.0,8219.0,8299.0,8370.0,8444.0,...,58963.0,59933.0,60848.0,61721.0,62564.0,63382.0,64172.0,64948.0,65720.0,66498.0
Finland,FIN,"Population, total",SP.POP.TOTL,4429634.0,4461005.0,4491443.0,4523309.0,4548543.0,4563732.0,4580869.0,...,5413971.0,5438972.0,5461512.0,5479531.0,5495303.0,5508214.0,5515525.0,5521606.0,5529543.0,5541696.0
Faroe Islands,FRO,"Population, total",SP.POP.TOTL,34624.0,35074.0,35521.0,35965.0,36409.0,36843.0,37283.0,...,47843.0,47901.0,47965.0,48055.0,48173.0,48326.0,48497.0,48677.0,48865.0,49053.0
Greenland,GRL,"Population, total",SP.POP.TOTL,32500.0,33700.0,35000.0,36400.0,37600.0,39200.0,40500.0,...,56810.0,56483.0,56295.0,56114.0,56186.0,56171.0,56023.0,56225.0,56367.0,56653.0
Ireland,IRL,"Population, total",SP.POP.TOTL,2828600.0,2824400.0,2836050.0,2852650.0,2866550.0,2877300.0,2888800.0,...,4599533.0,4623816.0,4657740.0,4701957.0,4755335.0,4807388.0,4867316.0,4934340.0,4985674.0,5028230.0
Iceland,ISL,"Population, total",SP.POP.TOTL,175574.0,179029.0,182378.0,185653.0,188983.0,192286.0,195570.0,...,320716.0,323764.0,327386.0,330815.0,335439.0,343400.0,352721.0,360563.0,366463.0,372295.0
Marshall Islands,MHL,"Population, total",SP.POP.TOTL,14674.0,15056.0,15547.0,16111.0,16710.0,17282.0,17834.0,...,56712.0,56933.0,57183.0,57444.0,57723.0,58053.0,58412.0,58791.0,59194.0,59618.0
Northern Mariana Islands,MNP,"Population, total",SP.POP.TOTL,9980.0,10243.0,10438.0,10591.0,10780.0,11023.0,11341.0,...,54306.0,54786.0,55301.0,55779.0,56187.0,56553.0,56889.0,57213.0,57557.0,57910.0
Netherlands,NLD,"Population, total",SP.POP.TOTL,11486631.0,11638712.0,11805689.0,11965966.0,12127120.0,12294732.0,12456251.0,...,16754962.0,16804432.0,16865008.0,16939923.0,17030314.0,17131296.0,17231624.0,17344874.0,17441500.0,17533405.0
New Zealand,NZL,"Population, total",SP.POP.TOTL,2371800.0,2419700.0,2482000.0,2531800.0,2585400.0,2628400.0,2675900.0,...,4408100.0,4442100.0,4516500.0,4609400.0,4714100.0,4813600.0,4900600.0,4979200.0,5090200.0,5122600.0
Poland,POL,"Population, total",SP.POP.TOTL,29637450.0,29964000.0,30308500.0,30712000.0,31139450.0,31444950.0,31681000.0,...,38063164.0,38040196.0,38011735.0,37986412.0,37970087.0,37974826.0,37974750.0,37965475.0,37899070.0,37781024.0
Pacific island small states,PSS,"Population, total",SP.POP.TOTL,865064.0,893394.0,923320.0,954098.0,984824.0,1014633.0,1043365.0,...,2268553.0,2295450.0,2323558.0,2353578.0,2385744.0,2419767.0,2455336.0,2491878.0,2528958.0,2566494.0
Solomon Islands,SLB,"Population, total",SP.POP.TOTL,117847.0,121385.0,125040.0,128838.0,132766.0,136815.0,140995.0,...,556066.0,571329.0,587079.0,603133.0,619438.0,636030.0,652856.0,669821.0,686878.0,703995.0
Turks and Caicos Islands,TCA,"Population, total",SP.POP.TOTL,5825.0,5867.0,5884.0,5870.0,5851.0,5814.0,5783.0,...,34067.0,34733.0,35371.0,35979.0,36558.0,37116.0,37667.0,38194.0,38718.0,39226.0
Thailand,THA,"Population, total",SP.POP.TOTL,27397208.0,28224186.0,29080945.0,29966873.0,30881136.0,31822656.0,32789129.0,...,67835969.0,68144519.0,68438748.0,68714519.0,68971313.0,69209817.0,69428454.0,69625581.0,69799978.0,69950844.0
British Virgin Islands,VGB,"Population, total",SP.POP.TOTL,8053.0,8164.0,8319.0,8469.0,8644.0,8836.0,9022.0,...,28654.0,28850.0,28985.0,29148.0,29355.0,29567.0,29795.0,30033.0,30237.0,30423.0
Virgin Islands (U.S.),VIR,"Population, total",SP.POP.TOTL,32500.0,34300.0,35000.0,39800.0,40800.0,43500.0,46200.0,...,108188.0,108041.0,107882.0,107712.0,107516.0,107281.0,107001.0,106669.0,106290.0,105870.0

---
### Sorting

They also want to get some better insights into their data so they ask you to also deliver these datasets to understand the population growth better:
- values sorted in ascending order by 1976
- values sorted in descending order by 2021

23. Values sorted by column 1976.

In [26]:
sol23 = df.sort_values(by='1976')
sol23

,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
Country Name,,,,,,,,,,,,,,,,,,,,,
Tuvalu,TUV,"Population, total",SP.POP.TOTL,5.321000e+03,5.330000e+03,5.340000e+03,5.341000e+03,5.354000e+03,5.388000e+03,5.435000e+03,...,1.074400e+04,1.084900e+04,1.097300e+04,1.109900e+04,1.123200e+04,1.136500e+04,1.150500e+04,1.165500e+04,1.179200e+04,1.192500e+04
Turks and Caicos Islands,TCA,"Population, total",SP.POP.TOTL,5.825000e+03,5.867000e+03,5.884000e+03,5.870000e+03,5.851000e+03,5.814000e+03,5.783000e+03,...,3.406700e+04,3.473300e+04,3.537100e+04,3.597900e+04,3.655800e+04,3.711600e+04,3.766700e+04,3.819400e+04,3.871800e+04,3.922600e+04
St. Martin (French part),MAF,"Population, total",SP.POP.TOTL,3.898000e+03,3.996000e+03,4.078000e+03,4.179000e+03,4.302000e+03,4.471000e+03,4.675000e+03,...,3.701200e+04,3.645800e+04,3.601800e+04,3.586500e+04,3.606100e+04,3.656900e+04,3.726400e+04,3.800200e+04,3.865900e+04,3.923900e+04
Nauru,NRU,"Population, total",SP.POP.TOTL,4.377000e+03,4.627000e+03,4.942000e+03,5.270000e+03,5.590000e+03,5.859000e+03,6.065000e+03,...,1.013600e+04,1.020800e+04,1.028900e+04,1.037400e+04,1.047400e+04,1.057700e+04,1.067800e+04,1.076400e+04,1.083400e+04,1.087300e+04
Sint Maarten (Dutch part),SXM,"Population, total",SP.POP.TOTL,2.833000e+03,3.077000e+03,3.367000e+03,3.703000e+03,4.063000e+03,4.460000e+03,4.895000e+03,...,3.464000e+04,3.660700e+04,3.768500e+04,3.882500e+04,3.996900e+04,4.057400e+04,4.089500e+04,4.160800e+04,4.231000e+04,4.284600e+04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Low & middle income,LMY,"Population, total",SP.POP.TOTL,2.244700e+09,2.273945e+09,2.316484e+09,2.371218e+09,2.426432e+09,2.483423e+09,2.544090e+09,...,5.869617e+09,5.948566e+09,6.027587e+09,6.106513e+09,6.185805e+09,6.265830e+09,6.343992e+09,6.420461e+09,6.494812e+09,6.566552e+09
IDA & IBRD total,IBT,"Population, total",SP.POP.TOTL,2.299245e+09,2.329155e+09,2.372381e+09,2.427869e+09,2.483840e+09,2.541415e+09,2.602627e+09,...,5.947406e+09,6.026674e+09,6.105863e+09,6.184735e+09,6.263736e+09,6.343293e+09,6.420905e+09,6.496952e+09,6.571053e+09,6.642614e+09
World,WLD,"Population, total",SP.POP.TOTL,3.032156e+09,3.071596e+09,3.124561e+09,3.189656e+09,3.255146e+09,3.322047e+09,3.392098e+09,...,7.089255e+09,7.175500e+09,7.261847e+09,7.347679e+09,7.433651e+09,7.519371e+09,7.602716e+09,7.683806e+09,7.763933e+09,7.836631e+09
Not classified,INX,"Population, total",SP.POP.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
West Bank and Gaza,PSE,"Population, total",SP.POP.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.979998e+06,4.076708e+06,4.173398e+06,4.270092e+06,4.367088e+06,4.454805e+06,4.569087e+06,4.685306e+06,4.803269e+06,4.922749e+06

>**Note:**   
Comparisons like this are very valuable to get a good understanding not only of your dataset but also the underlying data itself.   
For example, here we can see that the ranking of the lowest densely populated countries changed.

24. Values sorted by column 2021 in descending order.

In [27]:
sol24 = df.sort_values(by='2021', ascending=False)
sol24

,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
Country Name,,,,,,,,,,,,,,,,,,,,,
World,WLD,"Population, total",SP.POP.TOTL,3.032156e+09,3.071596e+09,3.124561e+09,3.189656e+09,3.255146e+09,3.322047e+09,3.392098e+09,...,7.089255e+09,7.175500e+09,7.261847e+09,7.347679e+09,7.433651e+09,7.519371e+09,7.602716e+09,7.683806e+09,7.763933e+09,7.836631e+09
IDA & IBRD total,IBT,"Population, total",SP.POP.TOTL,2.299245e+09,2.329155e+09,2.372381e+09,2.427869e+09,2.483840e+09,2.541415e+09,2.602627e+09,...,5.947406e+09,6.026674e+09,6.105863e+09,6.184735e+09,6.263736e+09,6.343293e+09,6.420905e+09,6.496952e+09,6.571053e+09,6.642614e+09
Low & middle income,LMY,"Population, total",SP.POP.TOTL,2.244700e+09,2.273945e+09,2.316484e+09,2.371218e+09,2.426432e+09,2.483423e+09,2.544090e+09,...,5.869617e+09,5.948566e+09,6.027587e+09,6.106513e+09,6.185805e+09,6.265830e+09,6.343992e+09,6.420461e+09,6.494812e+09,6.566552e+09
Middle income,MIC,"Population, total",SP.POP.TOTL,2.103847e+09,2.129932e+09,2.169233e+09,2.220611e+09,2.272301e+09,2.325560e+09,2.382277e+09,...,5.313946e+09,5.378523e+09,5.442820e+09,5.506549e+09,5.570151e+09,5.634011e+09,5.695494e+09,5.754729e+09,5.811279e+09,5.864625e+09
IBRD only,IBD,"Population, total",SP.POP.TOTL,1.919643e+09,1.940357e+09,1.974019e+09,2.019554e+09,2.065153e+09,2.111931e+09,2.161881e+09,...,4.518944e+09,4.566063e+09,4.612372e+09,4.657516e+09,4.701907e+09,4.746019e+09,4.787344e+09,4.826259e+09,4.862446e+09,4.895295e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Palau,PLW,"Population, total",SP.POP.TOTL,9.769000e+03,1.004600e+04,1.032900e+04,1.056600e+04,1.079200e+04,1.100500e+04,1.117800e+04,...,1.763500e+04,1.760300e+04,1.762500e+04,1.766500e+04,1.771800e+04,1.780900e+04,1.791100e+04,1.800100e+04,1.809200e+04,1.817400e+04
Tuvalu,TUV,"Population, total",SP.POP.TOTL,5.321000e+03,5.330000e+03,5.340000e+03,5.341000e+03,5.354000e+03,5.388000e+03,5.435000e+03,...,1.074400e+04,1.084900e+04,1.097300e+04,1.109900e+04,1.123200e+04,1.136500e+04,1.150500e+04,1.165500e+04,1.179200e+04,1.192500e+04
Nauru,NRU,"Population, total",SP.POP.TOTL,4.377000e+03,4.627000e+03,4.942000e+03,5.270000e+03,5.590000e+03,5.859000e+03,6.065000e+03,...,1.013600e+04,1.020800e+04,1.028900e+04,1.037400e+04,1.047400e+04,1.057700e+04,1.067800e+04,1.076400e+04,1.083400e+04,1.087300e+04
Eritrea,ERI,"Population, total",SP.POP.TOTL,1.007586e+06,1.033320e+06,1.060489e+06,1.088859e+06,1.118152e+06,1.148188e+06,1.178875e+06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Not classified,INX,"Population, total",SP.POP.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Reshaping

In order to create a visualization that focuses on 2015, they ask you to create a subset of your DataFrame which only contains one row that which holds all the values for the year 2015 mapped to the country codes as columns.

#### 25. Reshape to 2015 as row and country codes as columns.

In [28]:
sol25 = df[['2015']].T.rename(columns=df['Country Code'])
sol25

Country Name,ABW,AFE,AFG,AFW,AGO,ALB,AND,ARB,ARE,ARG,...,VIR,VNM,VUT,WLD,WSM,XKX,YEM,ZAF,ZMB,ZWE
2015,104339.0,593871847.0,34413603.0,401586651.0,27884380.0,2880703.0,77993.0,396028301.0,9262896.0,43131966.0,...,107712.0,92677082.0,271128.0,7.347679e+09,193510.0,1788196.0,26497881.0,55386369.0,15879370.0,13814642.0