<a href="https://colab.research.google.com/github/jiraroj-wir/MUIC-ICCS261-Principles-of-Data-Science/blob/main/read_pandas_Puzzle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Doing It Like `pandas`

Created by K. Bunchongchit (kritya.bun@mahidol.edu) <br>Last updated on Sept. 22, 2026

Last modified by _________________________ on __________

Most of the time in this class, we'll reading data from files and accessing those data rather than creating our own datasets from unstructured or semi-structured data. Thus, this notebook focuses on the intricacy of read operations in `pandas`. As mentioned before in class, some methods are only available via `Series` and some only via 'DataFrame`. If our operation does not result in the correct type, we cannot apply the property of method that we need to work efficiently. (Of course, there is a way to go around things, but using a trustable, available function will save you time and increase the accuracy of your program.)

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame({
    'Gold': [15, 12, 10],
    'Silver': [11, 9, 5] ,
    'Bronze': [6, 8, 12],
    'Continent': ['Europe', 'Asia', 'Asia']
    },
    ['France','China','Thailand'])
df

          Gold  Silver  Bronze Continent
France      15      11       6    Europe
China       12       9       8      Asia
Thailand    10       5      12      Asia

Below are some examples to demonstrate some property and method that are available only to `pandas Series`.

In [ ]:
df.is_monotonic_increasing

AttributeError: 'DataFrame' object has no attribute 'is_monotonic_increasing'

In [ ]:
df['Gold'].is_monotonic_increasing

False

In [ ]:
df.pct_change()

TypeError: unsupported operand type(s) for /: 'str' and 'str'

In [ ]:
df['Gold'].pct_change()

France           NaN
China      -0.200000
Thailand   -0.166667
Name: Gold, dtype: float64

So, let's dive into solving the puzzles below!

Write code to perform the following subsetting tasks on the DataFrame object `df` declared at the beginning of this notebook with numerical indices and column labels. Subsetting implies that you cannot create a new object from scratch. Using labels implies that you cannot use numerical indices.

## Part I: Getting a Specific Data Type

Use only labels indices/headers in this section. You may use `loc` and other pandas methods, but no numerical indices.

### 1.1 Access 8 as a literal.

### 1.2 Access 8 as a Series object and maintain its labels.

### 1.3 Access 8 as a DataFrame object and maintain its labels.

## Part II: Subsetting, `loc` and `iloc`

### 2.1 Get the intersection of the last two rows and the last two columns **without** use `loc` and `iloc`.

### 2.2 Get the intersection of the last two rows and the last two columns **with at least one** `loc`.

### 2.3 Get the intersection of the last two rows and the last two columns **with at least one** `iloc`.